logging:
  level:
    root: INFO

jpa:
  generate-ddl: false
  hibernate:
    ddl-auto: none
    dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    connection:
      driver_class: org.h2.Driver
      username: sa
      password: sa

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
#    driverClassName: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2
